CREATE TABLE person (
	person_id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	fName VARCHAR(30) NOT NULL,
	lName VARCHAR(50) NOT NULL,
	address VARCHAR(60) NOT NULL,
	postnumber CHAR(5) NOT NULL,
	city VARCHAR(20) NOT NULL,
	phone VARCHAR(10),
	email VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;

CREATE TABLE degree (
	degree_id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(30) NOT NULL,
	compYear INTEGER,
	school VARCHAR(50) NOT NULL,
	description TEXT,
	person_id INTEGER NOT NULL,
	FOREIGN KEY (person_id) REFERENCES person(person_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE workExperience (
	work_id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	employer VARCHAR(50) NOT NULL,
	title VARCHAR(30) NOT NULL,
	taskDescription TEXT,
	startDate DATE NOT NULL,
	endDate DATE,
	person_id INTEGER NOT NULL,
	FOREIGN KEY (person_id) REFERENCES person(person_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;

CREATE TABLE skill (
	skill_id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(30) NOT NULL,
	level VARCHAR(30) NOT NULL,
	person_id INTEGER NOT NULL,
	FOREIGN KEY (person_id) REFERENCES person(person_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;

CREATE TABLE authority (
  id integer NOT NULL auto_increment PRIMARY KEY,
  role varchar(255) NOT NULL UNIQUE
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 CREATE TABLE personAuthority (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  person_id INTEGER NOT NULL,
  authority_id INTEGER NOT NULL,
  FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (authority_id) REFERENCES authority(id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;